"use client"

import { Button } from "@relume_io/relume-ui";
import React from "react";
import { RxChevronRight } from "react-icons/rx";



export function Stats31() {
return (<section id="relume" className="px-[5%] py-16 md:py-24 lg:py-28"><div className="container"><div className="grid grid-cols-1 gap-y-12 lg:grid-cols-[0.5fr_1fr] lg:items-center lg:gap-x-20"><div><p className="mb-3 font-semibold md:mb-4">Proven</p><h2 className="mb-5 text-5xl font-bold md:mb-6 md:text-7xl lg:text-8xl">Results that speak for themselves</h2><p className="md:text-md">Organizations using Graph-AI Sentinel see dramatic improvements in incident handling and analyst efficiency. These metrics reflect real deployments across mid-to-large Sentinel environments.</p><div className="mt-6 flex flex-wrap items-center gap-4 md:mt-8"><Button title="Benchmark" variant="secondary">Benchmark</Button><Button title="Arrow" variant="link" size="link" iconRight={<RxChevronRight/>}>Arrow</Button></div></div><div className="grid grid-cols-1 gap-8 py-2 md:grid-cols-2"><div className="border border-border-primary p-8"><p className="mb-8 text-10xl font-bold leading-[1.3] md:mb-10 md:text-[4rem] lg:mb-12 lg:text-[5rem]">90%+</p><h3 className="text-md font-bold leading-[1.4] md:text-xl">Incidents auto-handled</h3><p className="mt-2">Routine incidents close or escalate without analyst intervention.</p></div><div className="border border-border-primary p-8"><p className="mb-8 text-10xl font-bold leading-[1.3] md:mb-10 md:text-[4rem] lg:mb-12 lg:text-[5rem]">50%</p><h3 className="text-md font-bold leading-[1.4] md:text-xl">False positives eliminated</h3><p className="mt-2">Graph-based reasoning cuts noise that rule-based systems miss.</p></div><div className="border border-border-primary p-8"><p className="mb-8 text-10xl font-bold leading-[1.3] md:mb-10 md:text-[4rem] lg:mb-12 lg:text-[5rem]">70%</p><h3 className="text-md font-bold leading-[1.4] md:text-xl">Faster mean time to resolution</h3><p className="mt-2">Autonomous triage and analysis compress incident lifecycle from hours to minutes.</p></div><div className="border border-border-primary p-8"><p className="mb-8 text-10xl font-bold leading-[1.3] md:mb-10 md:text-[4rem] lg:mb-12 lg:text-[5rem]">&lt;1 hour</p><h3 className="text-md font-bold leading-[1.4] md:text-xl">Deployment and integration</h3><p className="mt-2">Native Azure deployment connects to your Sentinel workspace with minimal setup.</p></div></div></div></div></section>);
}